"""Contribute a validated chain back to a commons source.

M11 (Chain Synthesis) and M20 (Chain Viewer) call into this module when an
analyst presses "Contribute". The signature accepts the chain payload as a
plain dict so the chain schema (M10) can evolve independently — anything
JSON-serialisable will do.

Contribution rules:
  * Only sources with ``contribute_enabled = TRUE`` are eligible.
  * The payload is filtered to ``tlp:clear`` before any PR is opened (public
    commons must not receive higher-classified content). The TLP filter is
    enforced here as a defensive last line; callers should already have
    stripped restricted fields per CLAUDE.md §7.
  * Anonymisation of org-local fields is the caller's responsibility — this
    module just opens the PR. The Chain Viewer / contribution UI in M20
    does the redaction step.
"""
from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone

import structlog
from sqlalchemy.ext.asyncio import AsyncSession

from fragchain.commons.sources import list_contribute_sources
from fragchain.commons.transport import CommonsTransport
from fragchain.db.models import CommonsSource

logger = structlog.get_logger(__name__)


@dataclass
class ContributeResult:
    source_id: str
    source_name: str
    status: str  # "submitted" | "skipped" | "error"
    pr_url: str | None = None
    pr_number: int | None = None
    branch: str | None = None
    message: str = ""


@dataclass
class ContributeBatchResult:
    cve_id: str
    per_source: list[ContributeResult] = field(default_factory=list)

    @property
    def submitted(self) -> int:
        return sum(1 for r in self.per_source if r.status == "submitted")

    @property
    def failures(self) -> int:
        return sum(1 for r in self.per_source if r.status == "error")


def _is_clear(tlp: str | None) -> bool:
    return (tlp or "tlp:clear").lower() == "tlp:clear"


async def contribute_to_source(
    source: CommonsSource,
    transport: CommonsTransport,
    *,
    cve_id: str,
    chain_payload: dict,
    actor_username: str | None = None,
) -> ContributeResult:
    """Open a PR against a single source. Never raises."""
    if not source.contribute_enabled:
        return ContributeResult(
            source_id=str(source.id),
            source_name=source.name,
            status="skipped",
            message="contribute_enabled=False",
        )
    if not _is_clear(chain_payload.get("tlp")):
        return ContributeResult(
            source_id=str(source.id),
            source_name=source.name,
            status="skipped",
            message=(
                f"chain TLP {chain_payload.get('tlp')!r} is above tlp:clear; "
                "public commons only accepts unrestricted content"
            ),
        )

    branch = f"fragchain/contrib/{cve_id.lower()}-{uuid.uuid4().hex[:8]}"
    title = f"Add chain for {cve_id}"
    actor = actor_username or "fragchain-bot"
    body_lines = [
        f"Contributed by `{actor}` at {datetime.now(timezone.utc).isoformat()}.",
        "",
        f"CVE: **{cve_id}**",
        f"Chain confidence: {chain_payload.get('overall_confidence', 'unknown')}",
        "",
        "This PR was generated by FragChain. See provenance in the chain "
        "payload for the originating model, prompt version, and validators.",
    ]
    body = "\n".join(body_lines)

    try:
        pr = await transport.create_chain_pr(
            cve_id=cve_id,
            chain_payload=chain_payload,
            branch=branch,
            title=title,
            body=body,
        )
    except Exception as exc:  # noqa: BLE001
        logger.exception(
            "commons.contribute.transport_failed",
            source_id=str(source.id),
            cve_id=cve_id,
        )
        return ContributeResult(
            source_id=str(source.id),
            source_name=source.name,
            status="error",
            branch=branch,
            message=f"transport error: {exc}",
        )

    if not pr.created:
        return ContributeResult(
            source_id=str(source.id),
            source_name=source.name,
            status="error",
            pr_url=pr.url,
            pr_number=pr.number,
            branch=pr.branch,
            message=pr.message,
        )

    logger.info(
        "commons.contribute.submitted",
        source_id=str(source.id),
        source_name=source.name,
        cve_id=cve_id,
        pr_number=pr.number,
        pr_url=pr.url,
    )
    return ContributeResult(
        source_id=str(source.id),
        source_name=source.name,
        status="submitted",
        pr_url=pr.url,
        pr_number=pr.number,
        branch=pr.branch,
        message=pr.message,
    )


async def contribute_chain(
    session: AsyncSession,
    *,
    cve_id: str,
    chain_payload: dict,
    actor_username: str | None = None,
    source_ids: list[uuid.UUID] | None = None,
    transport_factory=None,
) -> ContributeBatchResult:
    """Open PRs against every eligible source (or the ones listed in ``source_ids``).

    Returns a per-source breakdown — the caller (UI / API) can show users
    which contributions succeeded and which need manual follow-up.
    """
    if transport_factory is None:
        from fragchain.commons.factory import default_transport_factory
        transport_factory = default_transport_factory

    eligible = await list_contribute_sources(session)
    if source_ids is not None:
        wanted = {sid for sid in source_ids}
        eligible = [s for s in eligible if s.id in wanted]

    batch = ContributeBatchResult(cve_id=cve_id)
    for source in eligible:
        transport = transport_factory(source)
        try:
            outcome = await contribute_to_source(
                source,
                transport,
                cve_id=cve_id,
                chain_payload=chain_payload,
                actor_username=actor_username,
            )
        finally:
            try:
                await transport.aclose()
            except Exception:  # noqa: BLE001
                pass
        batch.per_source.append(outcome)
    return batch
